#!/usr/bin/env python3
"""Refresh sources.json from the Warhammer Community downloads index.

The downloads page (https://www.warhammer-community.com/en-gb/downloads/kill-team/)
renders its list client-side from a search endpoint. This queries that endpoint
directly, so every PDF link is the one the page currently shows, never a
hand-picked or web-searched URL (a stale search result once fed this project
January rules while the page already linked an August update).

- Every "team-rules" entry becomes teams.<id>, keyed by a slug of its title.
- Key downloads (lite rules, universal equipment, update logs, killzone and terrain
  documents) become core.<id>.
- Existing census ids keep their key via ALIASES.

Usage: sync_sources.py            # rewrite sources.json, print what changed
       sync_sources.py --check    # print changes only, exit 1 if anything is newer
"""
import json
import re
import sys
import urllib.request
from pathlib import Path

ENDPOINT = "https://www.warhammer-community.com/api/search/downloads/"
PAYLOAD = {"index": "downloads_v2", "searchTerm": "", "gameSystem": "kill-team", "language": "english"}
ASSETS = "https://assets.warhammer-community.com/"
SOURCES = Path(__file__).with_name("sources.json")
# census ids that predate slug-keys
ALIASES = {"angels_of_death": "aod"}
CORE = {"Kill Team Lite Rules": "lite_rules", "Universal Equipment": "universal_equipment",
        "Core Rules: Update Log": "core_update_log",
        # killzones, terrain and mission layout (for map-making, not the app)
        "Approved Ops 2025 Tournament Companion": "approved_ops",
        "Approved Ops: Update Log": "approved_ops_update_log",
        "Killzone Tomb World": "killzone_tomb_world",
        "Killzone: Tomb World Update Log": "killzone_tomb_world_update_log",
        "Exodite Architecture Terrain Templates": "exodite_terrain_templates"}


def slug(title):
    return re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")


def fetch():
    req = urllib.request.Request(
        ENDPOINT, data=json.dumps(PAYLOAD).encode(), method="POST",
        headers={"Content-Type": "application/json", "User-Agent": "Mozilla/5.0",
                 "Referer": "https://www.warhammer-community.com/en-gb/downloads/kill-team/"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)["hits"]


def entry(hit):
    i = hit["id"]
    f = i["file"]
    return {"title": i["title"], "url": f if f.startswith("http") else ASSETS + f,
            "lastUpdated": i.get("last_updated"), "fileSize": i.get("file_size")}


def main():
    check = "--check" in sys.argv
    old = json.loads(SOURCES.read_text(encoding="utf-8")) if SOURCES.exists() else {}
    teams, core = {}, {}
    for h in fetch():
        cats = h.get("download_categories", [])
        title = h["id"]["title"]
        if "team-rules" in cats:
            key = ALIASES.get(slug(title), slug(title))
            teams[key] = entry(h)
        elif title in CORE:
            core[CORE[title]] = entry(h)

    changed = []
    for group, new in (("teams", teams), ("core", core)):
        for k, e in sorted(new.items()):
            prev = old.get(group, {}).get(k, {})
            if prev.get("url") != e["url"]:
                changed.append(f"{group}.{k}: {e['lastUpdated']}  {prev.get('url', '(new)')} -> {e['url']}")
    for line in changed:
        print(line)
    print(f"{len(teams)} team documents, {len(core)} core documents; {len(changed)} changed")

    if check:
        sys.exit(1 if changed else 0)
    out = {
        "note": "Generated by sync_sources.py from the Warhammer Community downloads index — do not hand-edit URLs.",
        "downloadsPage": "https://www.warhammer-community.com/en-gb/downloads/kill-team/",
        "teams": teams,
        "core": core,
    }
    SOURCES.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
